name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # runs-on: self-hosted
    runs-on: ubuntu-latest
    timeout-minutes: 4320
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.811  
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --no-restore --framework netcoreapp2.1
    - name: Test
      run: |
        cd ./src/ObservableComputations.Test/
        dotnet restore
        dotnet test --framework netcoreapp2.1 -l "console;verbosity=normal" /p:CoverletOutput=TestResults/ /p:CollectCoverage=true /p:CoverletOutputFormat=lcov "/property:DefineConstants=`"GitHubActionBuild;RunOnlyMinimalTestsToCover`"" 
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./src/ObservableComputations.Test/TestResults/coverage.netcoreapp2.1.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./src/ObservableComputations.Test/TestResults/coverage.netcoreapp2.1.info
        flags: unittests
        name: codecov-umbrella
        verbose: true
